### ISSUE TITLE
Не могу подключить библиотеку

### ISSUE THREAD

**Issue by BloodFanger** [ResearcherNo1/Arduino_robot#3]
Выдаёт ошибку
exit status 1: Найдена неверная библиотека.

**Comment by BloodFanger** [comment]
Please help me.

**Comment by ResearcherNo1** [comment]
You need to *copy* folder with library *to the* _folder with sketch_
And in code you need write that stroke:
`#include "Motors.h"`

---
Вам необходимо *скопировать* папку с библиотекой *в папку* _со скетчем_
Также в код необходимо добавить следующую строку:
`#include "Motors.h"`
